# Basic Concepts

Printing

In [11]:
print('The year: {year}'.format(year=2020))

The year: 2020


Dictionary

In [8]:
d = {'Dog':'Poncho','Dog2':'Poncha'}
print(d['Dog'])

Poncho


List

In [15]:
x = [1,2,3,4]
out = []
for i in x:
    out.append(i**2)
print(out)

[1, 4, 9, 16]


Map

In [19]:
def times2(var):
    return var*2

seq = [1,2,3,4]
#list(map(times2,seq))
list(map(lambda num:num*2,seq))

[2, 4, 6, 8]

In [22]:
list(filter(lambda num: num%2==0,seq))

[2, 4]

Methods

In [28]:
st = 'My name is #Alvaro'
st.split('#')[1]

'Alvaro'

In [29]:
d

{'Dog': 'Poncho', 'Dog2': 'Poncha'}

In [31]:
print(d.keys())
print(d.items())

dict_keys(['Dog', 'Dog2'])
dict_items([('Dog', 'Poncho'), ('Dog2', 'Poncha')])


---

### Array

In [36]:
import numpy as np
m_list = [1,2,3]
np.array(m_list)

array([1, 2, 3])

In [38]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Methods

In [41]:
#High exclusive
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

Random

In [52]:
#standard normal
print(np.random.randn(2,2))
#random integers - high (exclusive)
print(np.random.randint(1,100,10))

[[-0.50349752 -0.51777262]
 [ 1.1896623  -0.20162796]]
[80 70 36 78 66 59 68  1 61 65]


In [69]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr.reshape(5,5))
print()
print(ranarr.reshape(2,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[13 10 38 40 49]
 [36 40 10  1  4]]


In [75]:
print(ranarr[0:2])
ranarr[:]=9
print(ranarr)

[13 10]
[9 9 9 9 9 9 9 9 9 9]


Selection

In [80]:
arr = np.random.randint(0,100,10)
arr

array([15, 68, 85, 99, 52, 68, 86, 34, 44, 84])

In [81]:
bool_arr = arr>60
print(bool_arr)

[False  True  True  True False  True  True False False  True]


In [83]:
arr[arr>60]

array([68, 85, 99, 68, 86, 84])